model:
  provider: "lfm2.5"
  model: "LiquidAI/LFM2.5-350M"
  tokenizer: "LiquidAI/LFM2.5-350M"
  max_length: 256

data:
  datasets:
    [
      "ramyibrahim/cniomt-ar-en-v1",
      "ramyibrahim/cniomt-ar-en-synth-v1",
      "ramyibrahim/cniomt-ar-en-synth-v2",
    ]
  split_ratio: 0.05

train:
  num_train_epochs: 3
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8

  logging_strategy: "epoch"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  load_best_model_at_end: True
  metric_for_best_model: "chrf"
  greater_is_better: True
  early_stopping: 2

  bf16: True
  optim: "paged_adamw_8bit"
  gradient_checkpointing: True
  learning_rate: 5e-5
  max_grad_norm: 1.0
  warmup_ratio: 0.10
  lr_scheduler_type: "cosine"
  predict_with_generate: True

  report_to: "wandb"
  run_name: "cniomt-ar-en-350M"
