model:
  provider: "opus"
  model: "Helsinki-NLP/opus-mt-ar-en"
  tokenizer: "Helsinki-NLP/opus-mt-ar-en"
  max_length: 256

data:
  datasets:
    [
      "ramyibrahim/cniomt-ar-en-v6",
      "ramyibrahim/holol-ar-en-synth-v1",
      "ramyibrahim/holol-ar-en-synth-v2",
    ]
  split_ratio: 0.01

train:
  num_train_epochs: 10
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16

  logging_strategy: "epoch"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  load_best_model_at_end: True
  metric_for_best_model: "chrf"
  greater_is_better: True
  early_stopping: 2

  bf16: True
  optim: "adamw_torch_fused"
  gradient_checkpointing: True
  learning_rate: 5e-5
  max_grad_norm: 0.10
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  predict_with_generate: True

  report_to: "wandb"
  run_name: "cnio-ar-en-v1-less"

  hub_model_id: "ramyibrahim/"
  push_to_hub: True
  hub_strategy: "end"
  hub_private_repo: False
