model:
  model_name: "Helsinki-NLP/opus-mt-ar-en"
  tokenizer_name: "Helsinki-NLP/opus-mt-ar-en"
  max_length: 256

data:
  data_name: "ramyibrahim/holol-ar-en-mt-v3"
  test_ratio: 0.01

train:
  num_train_epochs: 15
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16

  logging_strategy: "epoch"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  load_best_model_at_end: True
  metric_for_best_model: "chrf"
  greater_is_better: True
  early_stopping: 2

  bf16: True
  optim: "adamw_torch_fused"
  gradient_checkpointing: True
  learning_rate: 5e-5
  max_grad_norm: 0.10
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  predict_with_generate: True

  report_to: "wandb"
  run_name: "holol-ar-en-gamma-synth-v2"

  hub_model_id: "ramyibrahim/"
  push_to_hub: True
  hub_strategy: "end"
  hub_private_repo: False
